### ISSUE TITLE
More space-themed goodness

### ISSUE THREAD

**Issue by dar5hak** [im-in-space/mastodon#1]
It's great to see how you have customized the instance with the space theme. I was thinking that the instance users might have more such ideas… For example, "Toot!" could become "Launch!" or "Beam up!"? Can we discuss such ideas in this thread?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mkody** [comment]
I wasn't quite sure of what to use to replace the toot button, but I really like "Launch!"!

When I first customized the instance, the button was "SPACE!" but it doesn't look that fun when you're not tooting in public (the exclamation mark is removed, so it's like you're not shouting or sharing your excitement).

I'll leave this issue open to discuss about additional changes and I will share a link later. :wink:

**Comment by dar5hak** [comment]
Should "boosting" be called "relaunching" too? 🤔

**Comment by mkody** [comment]
"boost" is good enough, so your :rocket:  can fly further. :grin:

**Comment by dar5hak** [comment]
Hehe, makes sense! 😁
