### ISSUE TITLE
Move user roles in profile

### ISSUE THREAD

**Issue by mkody** [im-in-space/mastodon#4]
### Pitch

I'm thinking of moving it under the username ~~like Twitter's new "Official" label~~

![image](https://user-images.githubusercontent.com/843787/201348464-805dac0d-0cfa-4199-8ff7-376a03fcaf47.png)  
![image](https://user-images.githubusercontent.com/843787/201348486-afcbadc3-7f23-4a19-96e7-ab5f95410a60.png)

### Motivation

Making it inline doesn't look good with some long usernames or with how it shows up with the Modern theme.

**Comment by mkody** [comment]
Not sure if I remember this correctly but I think they were at the bottom of the profile. Doesn't look great to me.  
While implementing this I'll move the bot tag too.

**Comment by Roboron3042** [comment]
You can do it. I approve.

**Comment by mkody** [comment]
As a closing note: in the end I didn't move it under for the Modern theme (kind of a mess to deal with the flexbox there) so I made it go stick to the right

https://github.com/im-in-space/mastodon/blob/885193b175f945d45c712352722ec513dfa0eaf3/app/javascript/styles/modern/vanilla-diff.scss#L5-L15

![image](https://user-images.githubusercontent.com/843787/201725152-7ad4bf94-0ecb-492b-b216-2b2923250afa.png)
