### ISSUE TITLE
Blurry logo in the multicolumn mode

### ISSUE THREAD

**Issue by acid-bong** [im-in-space/mastodon#5]
### Steps to reproduce the problem

1. Enable multicolumn mode in settings
2. Go back to the main page

### Expected behaviour

Sharp logo in the lower left corner

### Actual behaviour

Blurry logo

### Detailed description

How it looks on im-in.space:
![изображение](https://user-images.githubusercontent.com/94849097/213938989-1ecc7861-f77d-4d79-b2cd-6e4060d7b32d.png)
(the picture is to compare the sharpness)

And how sharp it should look:
- vanilla logo (taken from issue 5736 in mastodon/mastodon)
![image](https://user-images.githubusercontent.com/4603019/41501247-b8ec49a6-716e-11e8-9b58-037c27619187.png)
- mstdn.social logo (taken from [Brodie Robertson's video](https://www.youtube.com/watch?v=ntFfKcbPvmI&t=73s))
![изображение](https://user-images.githubusercontent.com/94849097/213939217-c18a9729-fba0-4ede-a8a7-6e9c102271c0.png)
- space's own settings menu
![изображение](https://user-images.githubusercontent.com/94849097/213939294-610f475e-0594-4f8c-a54a-c18a320e853f.png)

### Specifications

Firefox 109 at the moment, but I remember it being blurry at least since about September, when i joined

**Comment by mkody** [comment]
Hi,

Yep, the size of the PNG isn't the same as the actual displayed size (and it might vary depending on the theme, wide mode on/off, screen size and the number of columns).
The way it appears blurry depends on how the browser renders it and if it's not "rounding" the pixels perfectly.

I'll change that to a SVG, it should prevent that.

**Comment by mkody** [comment]
Slightly rotated and the viewport is double its width, it should be good now.
Can you confirm it?

**Comment by acid-bong** [comment]
Checked with both vanilla-like and im-in.space themes, looks perfectly. Cheers
